link_board/config/routes.rb
Rails.application.routes.draw do

  root 'twins#index'
  resources :tags#, :except => [:destroy, :show, :create]
  resources :twins

end

link_board/app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :twins
end

link_board/app/models/tags_twins.rb
class TagsTwins < ActiveRecord::Base
  belongs_to :twin
  belongs_to :tag
end

link_board/app/models/twin.rb
class Twin < ActiveRecord::Base
  has_and_belongs_to_many :tags
end

link_board/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

link_board/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
    @twins = Twin.all
    @tag = Tag.new
  end
  def show
    @tag = Tag.find(params[:id])
    @twins = @tag.twins
  end
  def new
  end

  def create
    @tag = Tag.create(tag_params)
    redirect_to tags_path
    # if @tag.save
    #   render 'index'
    # else
    #   render 'root_path'
    # end
  end

  def destroy
     @tag = Tag.find(params[:id])

    unless @tag.twins.length > 0
      Tag.destroy(params[:id])
    else
      flash[:info] = "Cannot delete this tag. This tag belongs to #{@tag.twins.length} " + "Player".pluralize(@tag.twins.length)
    end

    redirect_to tags_path
  end
  private
    def tag_params
      params.require(:tag).permit(:name)
    end
end

link_board/app/controllers/twins_controller.rb
class TwinsController < ApplicationController
  def index
    @twin = Twin.all
  end

  def show
    @twin = Twin.find(params[:id])
    @tags = @twin.tags
    @tag = Tag.new
    # @tags << @tag
    # @twin.tags.clear
    # tags = params[:twin][:tag_ids]
    # tags.each do |tag_id|
    #  @twin.tags << Tag.find(tag_id) unless tag_id.blank?
    # end
    # if @twin.update(twin_params)
    #   redirect_to @twin
    # else
    #   render 'edit'
    # end
    # redirect_to twin_path

  end

  def new
    @twin = Twin.new
    @tags = Tag.all
  end

  def edit
    @twin = Twin.find(params[:id])
    @tags = Tag.all
  end

  def create
    @twin = Twin.new(twin_params)

    tags = params[:twin][:tag_ids]
    tags.each do |tag_id|
     @twin.tags << Tag.find(tag_id) unless tag_id.blank?
    end
    if @twin.save
      redirect_to @twin
    else
      render 'new'
    end
  end

  def update
    @twin = Twin.find(params[:id])
    @twin.tags.clear
    tags = params[:twin][:tag_ids]
    tags.each do |tag_id|
     @twin.tags << Tag.find(tag_id) unless tag_id.blank?
    end
    if @twin.update(twin_params)
      redirect_to @twin
    else
      render 'edit'
    end
  end
    private
    def twin_params
      params.require(:twin).permit(:name, :position, :number, :bio)
    end
    # def tag_params
    #   params.require(:tag).permit(:name)
    # end
end

link_board/app/helpers/application_helper.rb
module ApplicationHelper
end

link_board/app/helpers/tags_helper.rb
module TagsHelper
end

link_board/app/helpers/twins_helper.rb
module TwinsHelper
end

link_board/app/views/layouts/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %>">
    <%= v %>
  </div>
<% end %>

link_board/app/views/layouts/_form.html.erb
<%= bootstrap_form_for @twin do |f| %>

    <%= f.text_field :name, :placeholder => "Enter a Player" %>
    <%= f.text_field :position, :placeholder => "Enter a Position" %>
    <%= f.text_field :number, :placeholder => "Player's #" %>
    <%= f.text_area :bio, :placeholder => "Player Bio" %>
    <%= f.collection_check_boxes :tag_ids, @tags, :id, :name %>
    <%= f.submit %>




<% end %>

link_board/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>1991 MN Twins</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="blue">
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Full Roster", root_path %></li>
        <li><%= link_to "Add Player", new_twin_path %></li>
        <li><%= link_to "Tags", tags_path %></li>
        <!-- <li class="dropdown">s
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="This doesn't work... yet.">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <!-- <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container gray col-md-4 col-md-offset-4">
<%= yield %>
</div>
</body>
</html>

link_board/app/views/tags/index.html.erb
<h1>Tags</h1>
<%= bootstrap_form_for @tag do |f| %>
  <%= f.text_field :name, :placeholder => "Enter a new tag" %>
  <%= f.submit %>
<% end %>
<%= render "layouts/flash" %>
<hr>
<div class="table-responsive">
  <table class="table table-striped table-condensed">
    <% @tags.each do |t| %>
      <tr>
        <td><%= link_to t.name, t %></td>
        <td> <%= link_to raw("<i class=\"glyphicon glyphicon-trash\"></i>"), tag_path(t), :method => :delete, :class=>"btn btn-danger" %>
</td>
      </tr>
    <% end %>
  </table>
</div>
  <%= link_to '< Back', root_path %>

link_board/app/views/tags/new.html.erb
<h1>Create a new tag</h1>


<%= bootstrap_form_for @tag do |f| %>

    <%= f.text_field :name, :placeholder => "Enter a new tag" %>

    <%= f.submit %>




<% end %>

link_board/app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<div class="table-responsive">
  <table class="table table-striped table-condensed">
    <th>Players</th>
    <% @twins.each do |t| %>
    <tr>
      <td><%= link_to t.name, t %></li>
    </tr>
    <% end %>
  </table>
</div>

link_board/app/views/twins/edit.html.erb
<h1>Editing Player</h1>


<%= render "layouts/form" %>



<%= link_to 'Back', twins_path %>

link_board/app/views/twins/index.html.erb
<h1>1991 Minnesota Twins</h1>

<div class="table-responsive">
  <table class="table table-striped table-condensed">
    <% @twin.each do |p| %>
      <tr>
        <td>#<%= p.number %></td>
        <td><%= link_to p.name, p %></td>
        <td><%= p.position %></td>
        <td><%= link_to 'Edit Player', edit_twin_path(p) %></td>
      </tr>
    <% end %>
  <%= link_to 'Add Player', new_twin_path %>
  </table>
</div>

link_board/app/views/twins/new.html.erb
<h1>New Twins Player</h1>

<%= render "layouts/form" %>

<%= link_to 'Back', twins_path %>

link_board/app/views/twins/show.html.erb
<h1><%= @twin.name %></h1>

<p>
  <strong>Position:</strong>
  <%= @twin.position %>
</p>
<p>
  <strong>Number:</strong>
  <%= @twin.number %>
</p>
<p>
  <strong>Bio:</strong>
  <%= @twin.bio %>
</p>
<p><strong>Tags:</strong></p>
<% @tags.each do |t| %>
<ul>
 <li><%= link_to t.name, t %></li>
</ul>
<% end %>

<%= bootstrap_form_for @tag do |f| %>
  <%= f.text_field :name, :placeholder => "Enter a new tag" %>
  <%= f.submit %>
<% end %>

<%= link_to 'Edit Player', edit_twin_path(@twin) %> |
<%= link_to 'Full Roster', twins_path %>